### PR TITLE
Can we set other channel for telegram

### PR DESCRIPTION
**Pull request by 7x7x7eq51**

### CODE REVIEW

**Comment by 7x7x7eq51** [comment]
Hello, can you review it?

**Comment by 7x7x7eq51** [comment]
hello,

**Comment by hossainemruz** [comment]
@tranphuoctien we are extremely sorry to keep it hanging for long time. Actually, we are very busy with other projects. @tamalsaha will review it whenever he gets time. Also, we have to test it before merging.

**Comment by tamalsaha** [comment]
@tranphuoctien , I have merged your changes https://github.com/gomodules/notify/pull/39 . Thanks for sending the pr and patience.

**Pull request closed without merging**
